"use client";

import LegalPageLayout from "@/components/LegalPageLayout";

export default function TermsContent() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="March 17, 2026">
      <p>
        Welcome to BloggerSEO. By accessing or using our platform at <strong>bloggerseo.ai</strong>, you agree to be bound by these Terms of Service (&quot;Terms&quot;). Please read them carefully before using our services.
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By creating an account or using BloggerSEO, you agree to these Terms and our Privacy Policy. If you do not agree, you may not use our services. We reserve the right to modify these Terms at any time. Continued use after changes constitutes acceptance.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        BloggerSEO is an AI-powered content automation platform designed for Google Blogger users. Our services include:
      </p>
      <ul>
        <li>AI-generated SEO-optimized articles for Blogger</li>
        <li>Automatic publishing and scheduling to Blogger blogs</li>
        <li>Keyword research and content planning tools</li>
        <li>AI image generation for blog posts</li>
        <li>SEO site auditing and content optimization</li>
        <li>Bulk content generation and management</li>
        <li>Internal linking and content refresh tools</li>
      </ul>

      <h2>3. Account Registration</h2>
      <p>
        To use BloggerSEO, you must create an account using Google Sign-In. You are responsible for maintaining the security of your account credentials. You must be at least 16 years old to create an account. You agree to provide accurate and complete information during registration.
      </p>

      <h2>4. Subscription Plans and Payment</h2>
      <h3>4.1 Free Plan</h3>
      <p>
        We offer a free plan with limited features and usage quotas. Free plan users are subject to the same Terms as paid subscribers.
      </p>
      <h3>4.2 Paid Plans</h3>
      <p>
        Paid subscriptions are billed monthly or annually as selected during checkout. Prices are displayed in USD and are subject to change with 30 days&apos; notice. All payments are processed securely through our third-party payment provider.
      </p>
      <h3>4.3 Automatic Renewal</h3>
      <p>
        Paid subscriptions automatically renew at the end of each billing period unless cancelled before the renewal date. You may cancel at any time through your account settings.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree <strong>not</strong> to use BloggerSEO to:</p>
      <ul>
        <li>Generate content that is illegal, harmful, threatening, abusive, defamatory, or discriminatory</li>
        <li>Create spam, misleading content, or content designed to deceive</li>
        <li>Violate any applicable laws, regulations, or third-party rights</li>
        <li>Attempt to reverse-engineer, decompile, or hack our platform</li>
        <li>Circumvent usage limits or rate limits through automated means</li>
        <li>Resell or redistribute our services without written permission</li>
        <li>Generate content that infringes on intellectual property rights</li>
      </ul>

      <h2>6. Content Ownership and Responsibility</h2>
      <h3>6.1 Your Content</h3>
      <p>
        You retain ownership of the content you generate using BloggerSEO. You are solely responsible for the content published to your blog, including ensuring it complies with applicable laws, does not infringe on third-party rights, and meets Google Blogger&apos;s terms of service.
      </p>
      <h3>6.2 AI-Generated Content</h3>
      <p>
        Content generated by our AI tools is provided as-is. While we strive for accuracy, AI-generated content may contain errors, inaccuracies, or outdated information. You are responsible for reviewing and editing all content before publishing. BloggerSEO does not guarantee that AI-generated content is factually accurate, original, or suitable for any particular purpose.
      </p>

      <h2>7. Google API Usage</h2>
      <p>
        BloggerSEO integrates with Google APIs to access and publish content to your Blogger blogs. By connecting your Google account, you authorize us to access your Blogger data as described in our Privacy Policy. Our use of Google data complies with the <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer">Google API Services User Data Policy</a>.
      </p>

      <h2>8. Service Availability</h2>
      <p>
        We strive to maintain high availability but do not guarantee uninterrupted service. BloggerSEO may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control. We are not liable for any damages resulting from service interruptions.
      </p>

      <h2>9. Intellectual Property</h2>
      <p>
        The BloggerSEO platform, including its design, code, features, and branding, is our intellectual property. You may not copy, modify, distribute, or create derivative works based on our platform without written consent.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, BloggerSEO and its team shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising from your use of our services. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify and hold BloggerSEO harmless from any claims, damages, losses, or expenses arising from your use of our services, your content, or your violation of these Terms.
      </p>

      <h2>12. Termination</h2>
      <p>
        We may suspend or terminate your account at any time for violation of these Terms or for any reason at our discretion. Upon termination, your right to use our services ceases immediately. You may also delete your account at any time through your account settings.
      </p>

      <h2>13. Governing Law</h2>
      <p>
        These Terms are governed by and construed in accordance with applicable laws. Any disputes arising from these Terms shall be resolved through binding arbitration or in the courts of competent jurisdiction.
      </p>

      <h2>14. Contact</h2>
      <p>
        For questions about these Terms, contact us at <a href="mailto:support@bloggerseowriting.com">support@bloggerseowriting.com</a>.
      </p>
    </LegalPageLayout>
  );
}
