"use client";

import LegalPageLayout from "@/components/LegalPageLayout";

export default function DisclaimerContent() {
  return (
    <LegalPageLayout title="Disclaimer" lastUpdated="March 17, 2026">
      <p>
        The information provided by BloggerSEO (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) on <strong>bloggerseo.ai</strong> is for general informational purposes. By using our platform, you acknowledge and agree to the following disclaimers.
      </p>

      <h2>1. AI-Generated Content Disclaimer</h2>
      <p>
        BloggerSEO uses artificial intelligence to generate articles, images, and other content. While we strive for accuracy and quality, AI-generated content may contain errors, inaccuracies, outdated information, or unintended biases. You are solely responsible for reviewing, editing, and verifying all AI-generated content before publishing it to your blog or using it for any purpose.
      </p>
      <p>
        We do <strong>not</strong> guarantee that AI-generated content is:
      </p>
      <ul>
        <li>100% factually accurate or up-to-date</li>
        <li>Free from plagiarism or copyright issues</li>
        <li>Suitable for any specific legal, medical, financial, or professional purpose</li>
        <li>Compliant with all local laws and regulations in your jurisdiction</li>
      </ul>

      <h2>2. No Professional Advice</h2>
      <p>
        Content generated through BloggerSEO does not constitute professional advice of any kind — including but not limited to legal, medical, financial, or tax advice. Always consult qualified professionals before making decisions based on information in generated articles.
      </p>

      <h2>3. SEO Results Disclaimer</h2>
      <p>
        BloggerSEO provides tools and features designed to optimize content for search engines. However, we do <strong>not</strong> guarantee any specific search engine rankings, traffic levels, or business results. Search engine algorithms are complex and change frequently. Your results may vary based on factors outside our control, including competition, domain authority, niche, content quality, and technical SEO factors.
      </p>

      <h2>4. Third-Party Services</h2>
      <p>
        Our platform integrates with third-party services including Google Blogger, Google Analytics, and AI model providers. We are not responsible for the availability, accuracy, or reliability of these third-party services. Changes to third-party APIs or terms of service may affect our platform&apos;s functionality.
      </p>

      <h2>5. External Links</h2>
      <p>
        AI-generated articles may contain links to external websites. We do not control and are not responsible for the content, privacy practices, or availability of third-party websites. The inclusion of external links does not imply endorsement of their content or views.
      </p>

      <h2>6. Earnings and Income Disclaimer</h2>
      <p>
        Any references to earnings, revenue, or income potential on our website or in generated content are for illustrative purposes only. Individual results vary significantly and depend on many factors beyond our control. We do not guarantee that using BloggerSEO will result in any specific financial outcomes.
      </p>

      <h2>7. Affiliate Disclosure</h2>
      <p>
        Some content generated through BloggerSEO may contain affiliate links if you choose to include them. Users are responsible for complying with applicable affiliate disclosure requirements (such as FTC guidelines) when publishing content with affiliate links.
      </p>

      <h2>8. Image Generation Disclaimer</h2>
      <p>
        Images generated by our AI tools are created algorithmically and may not always be perfectly accurate representations of real-world subjects. Generated images should not be used in ways that could mislead viewers about real people, places, or events.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, BloggerSEO shall not be liable for any damages arising from your use of our platform or reliance on AI-generated content. This includes but is not limited to direct, indirect, incidental, consequential, or punitive damages.
      </p>

      <h2>10. Changes to This Disclaimer</h2>
      <p>
        We may update this Disclaimer at any time. Changes will be posted on this page with an updated date. Your continued use of BloggerSEO constitutes acceptance of any changes.
      </p>

      <h2>11. Contact</h2>
      <p>
        If you have questions about this Disclaimer, contact us at <a href="mailto:support@bloggerseo.ai">support@bloggerseo.ai</a>.
      </p>
    </LegalPageLayout>
  );
}
